# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import pokemon_pb2 as pokemon__pb2


class PokemonsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Checkboard = channel.unary_unary(
                '/ou_pokemon.Pokemons/Checkboard',
                request_serializer=pokemon__pb2.BoardConfig.SerializeToString,
                response_deserializer=pokemon__pb2.MoveDecision.FromString,
                )
        self.Move = channel.unary_unary(
                '/ou_pokemon.Pokemons/Move',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Trainer = channel.unary_unary(
                '/ou_pokemon.Pokemons/Trainer',
                request_serializer=pokemon__pb2.TrainerName.SerializeToString,
                response_deserializer=pokemon__pb2.TrainerInfo.FromString,
                )
        self.Path = channel.unary_unary(
                '/ou_pokemon.Pokemons/Path',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pokemon__pb2.MoveList.FromString,
                )


class PokemonsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Checkboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Path(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokemonsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Checkboard': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkboard,
                    request_deserializer=pokemon__pb2.BoardConfig.FromString,
                    response_serializer=pokemon__pb2.MoveDecision.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Trainer': grpc.unary_unary_rpc_method_handler(
                    servicer.Trainer,
                    request_deserializer=pokemon__pb2.TrainerName.FromString,
                    response_serializer=pokemon__pb2.TrainerInfo.SerializeToString,
            ),
            'Path': grpc.unary_unary_rpc_method_handler(
                    servicer.Path,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pokemon__pb2.MoveList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ou_pokemon.Pokemons', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pokemons(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Checkboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.Pokemons/Checkboard',
            pokemon__pb2.BoardConfig.SerializeToString,
            pokemon__pb2.MoveDecision.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.Pokemons/Move',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Trainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.Pokemons/Trainer',
            pokemon__pb2.TrainerName.SerializeToString,
            pokemon__pb2.TrainerInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Path(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.Pokemons/Path',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pokemon__pb2.MoveList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
