# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemonou.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpokemonou.proto\x12\nou_pokemon\"\x18\n\x08Hostname\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\x0cInitialMoves\x12\r\n\x05\x65xist\x18\x01 \x01(\t\"\x1b\n\x07PokMove\x12\x10\n\x08hostname\x18\x01 \x01(\t\"\x1d\n\tTrainMove\x12\x10\n\x08hostname\x18\x01 \x01(\t\"\x18\n\x07Message\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32\xc2\x01\n\rOUPokemanGame\x12\x39\n\x05\x42oard\x12\x14.ou_pokemon.Hostname\x1a\x18.ou_pokemon.InitialMoves\"\x00\x12;\n\x0bTrainerMove\x12\x15.ou_pokemon.TrainMove\x1a\x13.ou_pokemon.Message\"\x00\x12\x39\n\x0bPokemonMove\x12\x13.ou_pokemon.PokMove\x1a\x13.ou_pokemon.Message\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pokemonou_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HOSTNAME._serialized_start=31
  _HOSTNAME._serialized_end=55
  _INITIALMOVES._serialized_start=57
  _INITIALMOVES._serialized_end=86
  _POKMOVE._serialized_start=88
  _POKMOVE._serialized_end=115
  _TRAINMOVE._serialized_start=117
  _TRAINMOVE._serialized_end=146
  _MESSAGE._serialized_start=148
  _MESSAGE._serialized_end=172
  _OUPOKEMANGAME._serialized_start=175
  _OUPOKEMANGAME._serialized_end=369
# @@protoc_insertion_point(module_scope)
