# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpokemon.proto\x12\nou_pokemon\x1a\x1bgoogle/protobuf/empty.proto\"*\n\x0b\x42oardConfig\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\x05\"\x1c\n\x0cMoveDecision\x12\x0c\n\x04move\x18\x01 \x01(\t\"\x1c\n\x0bTrainerName\x12\r\n\x05tname\x18\x01 \x01(\t\"H\n\x0bTrainerInfo\x12\r\n\x05tname\x18\x01 \x01(\t\x12\r\n\x05pname\x18\x02 \x01(\t\x12\x0b\n\x03row\x18\x03 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x04 \x01(\x05\"6\n\x08MoveList\x12*\n\x08movelist\x18\x01 \x03(\x0b\x32\x18.ou_pokemon.MoveDecision2\xfe\x01\n\x08Pokemons\x12\x41\n\nCheckboard\x12\x17.ou_pokemon.BoardConfig\x1a\x18.ou_pokemon.MoveDecision\"\x00\x12\x38\n\x04Move\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12=\n\x07Trainer\x12\x17.ou_pokemon.TrainerName\x1a\x17.ou_pokemon.TrainerInfo\"\x00\x12\x36\n\x04Path\x12\x16.google.protobuf.Empty\x1a\x14.ou_pokemon.MoveList\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pokemon_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOARDCONFIG._serialized_start=58
  _BOARDCONFIG._serialized_end=100
  _MOVEDECISION._serialized_start=102
  _MOVEDECISION._serialized_end=130
  _TRAINERNAME._serialized_start=132
  _TRAINERNAME._serialized_end=160
  _TRAINERINFO._serialized_start=162
  _TRAINERINFO._serialized_end=234
  _MOVELIST._serialized_start=236
  _MOVELIST._serialized_end=290
  _POKEMONS._serialized_start=293
  _POKEMONS._serialized_end=547
# @@protoc_insertion_point(module_scope)
