# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pokemonou_pb2 as pokemonou__pb2


class OUPokemanGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Board = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/Board',
                request_serializer=pokemonou__pb2.Hostname.SerializeToString,
                response_deserializer=pokemonou__pb2.InitialMoves.FromString,
                )
        self.TrainerMove = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/TrainerMove',
                request_serializer=pokemonou__pb2.TrainMove.SerializeToString,
                response_deserializer=pokemonou__pb2.Message.FromString,
                )
        self.PokemonMove = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/PokemonMove',
                request_serializer=pokemonou__pb2.PokMove.SerializeToString,
                response_deserializer=pokemonou__pb2.Message.FromString,
                )


class OUPokemanGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Board(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainerMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PokemonMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OUPokemanGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Board': grpc.unary_unary_rpc_method_handler(
                    servicer.Board,
                    request_deserializer=pokemonou__pb2.Hostname.FromString,
                    response_serializer=pokemonou__pb2.InitialMoves.SerializeToString,
            ),
            'TrainerMove': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainerMove,
                    request_deserializer=pokemonou__pb2.TrainMove.FromString,
                    response_serializer=pokemonou__pb2.Message.SerializeToString,
            ),
            'PokemonMove': grpc.unary_unary_rpc_method_handler(
                    servicer.PokemonMove,
                    request_deserializer=pokemonou__pb2.PokMove.FromString,
                    response_serializer=pokemonou__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ou_pokemon.OUPokemanGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OUPokemanGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Board(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/Board',
            pokemonou__pb2.Hostname.SerializeToString,
            pokemonou__pb2.InitialMoves.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainerMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/TrainerMove',
            pokemonou__pb2.TrainMove.SerializeToString,
            pokemonou__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PokemonMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/PokemonMove',
            pokemonou__pb2.PokMove.SerializeToString,
            pokemonou__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
