# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import pokemonou_pb2 as pokemonou__pb2


class OUPokemanGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Captured = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/Captured',
                request_serializer=pokemonou__pb2.PokemonName.SerializeToString,
                response_deserializer=pokemonou__pb2.PokemonName.FromString,
                )
        self.Moves = channel.stream_stream(
                '/ou_pokemon.OUPokemanGame/Moves',
                request_serializer=pokemonou__pb2.Player.SerializeToString,
                response_deserializer=pokemonou__pb2.Feedback.FromString,
                )
        self.Board = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/Board',
                request_serializer=pokemonou__pb2.BoardConfig.SerializeToString,
                response_deserializer=pokemonou__pb2.BoardConfig.FromString,
                )
        self.Checkboard = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/Checkboard',
                request_serializer=pokemonou__pb2.BoardConfig.SerializeToString,
                response_deserializer=pokemonou__pb2.MoveDecision.FromString,
                )
        self.TrainerMove = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/TrainerMove',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Trainer = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/Trainer',
                request_serializer=pokemonou__pb2.TrainerName.SerializeToString,
                response_deserializer=pokemonou__pb2.TrainerInfo.FromString,
                )
        self.TrainerPath = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/TrainerPath',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pokemonou__pb2.MoveList.FromString,
                )
        self.Capture = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/Capture',
                request_serializer=pokemonou__pb2.Message.SerializeToString,
                response_deserializer=pokemonou__pb2.Message.FromString,
                )
        self.PokemonMove = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/PokemonMove',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Pokedex = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/Pokedex',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pokemonou__pb2.PokemonList.FromString,
                )
        self.PokemonPath = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/PokemonPath',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pokemonou__pb2.MoveList.FromString,
                )


class OUPokemanGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Captured(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Moves(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Board(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainerMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainerPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Capture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PokemonMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pokedex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PokemonPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OUPokemanGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Captured': grpc.unary_unary_rpc_method_handler(
                    servicer.Captured,
                    request_deserializer=pokemonou__pb2.PokemonName.FromString,
                    response_serializer=pokemonou__pb2.PokemonName.SerializeToString,
            ),
            'Moves': grpc.stream_stream_rpc_method_handler(
                    servicer.Moves,
                    request_deserializer=pokemonou__pb2.Player.FromString,
                    response_serializer=pokemonou__pb2.Feedback.SerializeToString,
            ),
            'Board': grpc.unary_unary_rpc_method_handler(
                    servicer.Board,
                    request_deserializer=pokemonou__pb2.BoardConfig.FromString,
                    response_serializer=pokemonou__pb2.BoardConfig.SerializeToString,
            ),
            'Checkboard': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkboard,
                    request_deserializer=pokemonou__pb2.BoardConfig.FromString,
                    response_serializer=pokemonou__pb2.MoveDecision.SerializeToString,
            ),
            'TrainerMove': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainerMove,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Trainer': grpc.unary_unary_rpc_method_handler(
                    servicer.Trainer,
                    request_deserializer=pokemonou__pb2.TrainerName.FromString,
                    response_serializer=pokemonou__pb2.TrainerInfo.SerializeToString,
            ),
            'TrainerPath': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainerPath,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pokemonou__pb2.MoveList.SerializeToString,
            ),
            'Capture': grpc.unary_unary_rpc_method_handler(
                    servicer.Capture,
                    request_deserializer=pokemonou__pb2.Message.FromString,
                    response_serializer=pokemonou__pb2.Message.SerializeToString,
            ),
            'PokemonMove': grpc.unary_unary_rpc_method_handler(
                    servicer.PokemonMove,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Pokedex': grpc.unary_unary_rpc_method_handler(
                    servicer.Pokedex,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pokemonou__pb2.PokemonList.SerializeToString,
            ),
            'PokemonPath': grpc.unary_unary_rpc_method_handler(
                    servicer.PokemonPath,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pokemonou__pb2.MoveList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ou_pokemon.OUPokemanGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OUPokemanGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Captured(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/Captured',
            pokemonou__pb2.PokemonName.SerializeToString,
            pokemonou__pb2.PokemonName.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Moves(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ou_pokemon.OUPokemanGame/Moves',
            pokemonou__pb2.Player.SerializeToString,
            pokemonou__pb2.Feedback.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Board(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/Board',
            pokemonou__pb2.BoardConfig.SerializeToString,
            pokemonou__pb2.BoardConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Checkboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/Checkboard',
            pokemonou__pb2.BoardConfig.SerializeToString,
            pokemonou__pb2.MoveDecision.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainerMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/TrainerMove',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Trainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/Trainer',
            pokemonou__pb2.TrainerName.SerializeToString,
            pokemonou__pb2.TrainerInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainerPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/TrainerPath',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pokemonou__pb2.MoveList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Capture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/Capture',
            pokemonou__pb2.Message.SerializeToString,
            pokemonou__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PokemonMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/PokemonMove',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Pokedex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/Pokedex',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pokemonou__pb2.PokemonList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PokemonPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/PokemonPath',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pokemonou__pb2.MoveList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
