# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pokemonou_pb2 as pokemonou__pb2


class OUPokemanGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Captured = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/Captured',
                request_serializer=pokemonou__pb2.PokemonName.SerializeToString,
                response_deserializer=pokemonou__pb2.PokemonName.FromString,
                )
        self.Moves = channel.stream_stream(
                '/ou_pokemon.OUPokemanGame/Moves',
                request_serializer=pokemonou__pb2.Player.SerializeToString,
                response_deserializer=pokemonou__pb2.Feedback.FromString,
                )
        self.Board = channel.unary_unary(
                '/ou_pokemon.OUPokemanGame/Board',
                request_serializer=pokemonou__pb2.BoardConfig.SerializeToString,
                response_deserializer=pokemonou__pb2.BoardConfig.FromString,
                )


class OUPokemanGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Captured(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Moves(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Board(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OUPokemanGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Captured': grpc.unary_unary_rpc_method_handler(
                    servicer.Captured,
                    request_deserializer=pokemonou__pb2.PokemonName.FromString,
                    response_serializer=pokemonou__pb2.PokemonName.SerializeToString,
            ),
            'Moves': grpc.stream_stream_rpc_method_handler(
                    servicer.Moves,
                    request_deserializer=pokemonou__pb2.Player.FromString,
                    response_serializer=pokemonou__pb2.Feedback.SerializeToString,
            ),
            'Board': grpc.unary_unary_rpc_method_handler(
                    servicer.Board,
                    request_deserializer=pokemonou__pb2.BoardConfig.FromString,
                    response_serializer=pokemonou__pb2.BoardConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ou_pokemon.OUPokemanGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OUPokemanGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Captured(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/Captured',
            pokemonou__pb2.PokemonName.SerializeToString,
            pokemonou__pb2.PokemonName.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Moves(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ou_pokemon.OUPokemanGame/Moves',
            pokemonou__pb2.Player.SerializeToString,
            pokemonou__pb2.Feedback.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Board(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.OUPokemanGame/Board',
            pokemonou__pb2.BoardConfig.SerializeToString,
            pokemonou__pb2.BoardConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
