# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import trainer_pb2 as trainer__pb2


class PokemonTrainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Capture = channel.unary_unary(
                '/ou_pokemon.PokemonTrainer/Capture',
                request_serializer=trainer__pb2.Feedback.SerializeToString,
                response_deserializer=trainer__pb2.Feedback.FromString,
                )
        self.Checkboard = channel.unary_unary(
                '/ou_pokemon.PokemonTrainer/Checkboard',
                request_serializer=trainer__pb2.BoardConfig.SerializeToString,
                response_deserializer=trainer__pb2.MoveDecision.FromString,
                )
        self.Move = channel.unary_unary(
                '/ou_pokemon.PokemonTrainer/Move',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Pokedex = channel.unary_unary(
                '/ou_pokemon.PokemonTrainer/Pokedex',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=trainer__pb2.PokemonList.FromString,
                )
        self.Path = channel.unary_unary(
                '/ou_pokemon.PokemonTrainer/Path',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=trainer__pb2.MoveList.FromString,
                )


class PokemonTrainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Capture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pokedex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Path(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokemonTrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Capture': grpc.unary_unary_rpc_method_handler(
                    servicer.Capture,
                    request_deserializer=trainer__pb2.Feedback.FromString,
                    response_serializer=trainer__pb2.Feedback.SerializeToString,
            ),
            'Checkboard': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkboard,
                    request_deserializer=trainer__pb2.BoardConfig.FromString,
                    response_serializer=trainer__pb2.MoveDecision.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Pokedex': grpc.unary_unary_rpc_method_handler(
                    servicer.Pokedex,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=trainer__pb2.PokemonList.SerializeToString,
            ),
            'Path': grpc.unary_unary_rpc_method_handler(
                    servicer.Path,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=trainer__pb2.MoveList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ou_pokemon.PokemonTrainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PokemonTrainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Capture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.PokemonTrainer/Capture',
            trainer__pb2.Feedback.SerializeToString,
            trainer__pb2.Feedback.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Checkboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.PokemonTrainer/Checkboard',
            trainer__pb2.BoardConfig.SerializeToString,
            trainer__pb2.MoveDecision.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.PokemonTrainer/Move',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Pokedex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.PokemonTrainer/Pokedex',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            trainer__pb2.PokemonList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Path(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ou_pokemon.PokemonTrainer/Path',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            trainer__pb2.MoveList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
